# https://taskfile.dev

version: '3'


tasks:
  build:
    desc: Build for Docker Hub
    cmds:
      - docker buildx build -t alastairhm/shellcheck:latest ./
    silent: true
  push:
    desc: Push to Docker Hub
    cmds:
      - docker push alastairhm/shellcheck:latest
    silent: true
